name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          # GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # meta
          API_BASE_URL: https://wakatime.com/api
          REPOSITORY: Fuckners/Fuckners
          # content
          SECTION_NAME: waka
          LANG_COUNT: 10
          SHOW_TOTAL: true
          TIME_RANGE: all_time
          BLOCKS: -+
          # commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
          TARGET_BRANCH: main
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.org
          # you can populate email-id with secretes instead